server:
  port: 8081


spring:
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002 # 카프카 서버 주소
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: error-handler-group
      auto-offset-reset: earliest
    template:
      default-topic: error-messages

