version: '3.8'

services:
  mongodb:
    image: mongo:6.0.22  # MongoDB 버전 6.0.22 사용
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.12.5  # Qdrant 최신 버전 사용
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__ENABLE_UI: true  # 내장 Web UI 활성화
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
