spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/haxgonal
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
