version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.12.5  # Qdrant 최신 안정 버전
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API
    environment:
      QDRANT__SERVICE__ENABLE_UI: true  # 내장 Web UI 활성화
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
